=== chengluo331/inpranet/Indexation/src/main/resources/document.dtd
<!ELEMENT document (metaData, data)>
<!ELEMENT metaData (reference, title, uri, categoriesList, temporalCreationData, temporalSourceData, geographicalSourceData)>
<!ELEMENT reference (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT uri (#PCDATA)>
<!ELEMENT categoriesList (category+)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT temporalCreationData (#PCDATA)>
<!ELEMENT temporalSourceData (temporalSourceStartData, temporalSourceEndData)>
<!ELEMENT temporalSourceStartData (#PCDATA)>
<!ELEMENT temporalSourceEndData (#PCDATA)>
<!ELEMENT geographicalSourceData (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ATTLIST document
	urgent CDATA #REQUIRED
>
<!ATTLIST categoriesList
	categoriesSourceReliable CDATA #REQUIRED
>
<!ATTLIST temporalSourceData
	temporalSourceReliable CDATA #REQUIRED
>
<!ATTLIST geographicalSourceData
	geographicalSourceReliable CDATA #REQUIRED
>

=== chengluo331/inpranet/trunk/Indexation/src/main/resources/document.xml
<?xml version="1.0"?>
<!DOCTYPE document SYSTEM "document.dtd">
<document urgent="true">
	<metaData>
		<reference>KARNAVAL-2011</reference>
		<title>Semaine de la Solidarité - Karnaval Humanitaire 17 au 13 avril 2011</title>
		<uri>http://envue.insa-lyon.fr/2011mars/art5_0311.php#karnaval</uri>
		<categoriesList categoriesSourceReliable="true">
			<category>Scolaire</category>
		</categoriesList>
		<temporalCreationData>03-2011</temporalCreationData>
		<temporalSourceData temporalSourceReliable="false">
			<temporalSourceStartData>00:00</temporalSourceStartData>
			<temporalSourceEndData>23:59</temporalSourceEndData>
		</temporalSourceData>
		<geographicalSourceData geographicalSourceReliable="true">
			INSA de Lyon
		</geographicalSourceData>
	</metaData>
	<data>
		Le Karnaval Humanitaire est né de l'initiative très originale d'associer festival et action de solidarité. Une grande fête organisée autour d'un défilé qui rassemble les enfants de Villeurbanne et les étudiants du campus. Les fonds récoltés pendant cette semaine de festivités permettent de financer un projet de solidarité internationale. Ce projet baptisé « Eau Pour Tous » a été mis en place en 2006 en partenariat avec l'AJS Burkina (Association Jeunesse Solide) dans le but de faciliter l'accès à l'eau potable à Pella, un petit village du Burkina Faso. Chaque année de nouveau travaux sont réalisés et un système d'autogestion est progressivement mis en place pour que le village puisse utiliser ses installations hydrauliques en parfaite autonomie. La Semaine de la Solidarité est devenue au fil des années l’un des événements incontournables de la fin d’hiver à Lyon. Aujourd'hui, c'est plus de 20.000 personnes qui participent à cette manifestation, notamment pendant le défilé déguisé, qui rassemble petits et grands dans une ambiance joyeuse et colorée.
		Résumé du programme : Jeudi 17 mars : sur le thème des Cultures Régionales et Traditionnelles. Lundi 21 mars : Conférence et débat sur le thème de l'immigration de 19h30 à 22h30 (gratuit). Mardi 22 mars : Projection et débat sur "la marche de l'égalité" de 19h30 à 23h (gratuit). Mercredi 23 mars : Koncert : La marmite (3€ ou lancé de dé / gratuit pour les enfants). Jeudi 24 mars : - Défilé avec les enfants des écoles de Villeurbanne (Parcours à travers Villeurbanne avec des chars et les enfants déguisés). Vendredi 25 mars : Koncert : Darkham / Konrad Kuechenmeister / Stand High Patrol (7€ sur place / 5€ prévente). Mercredi 13 avril : Koncert : Paracétamol / Z.E.P. / KKC Orchestra (7€ sur place / 5€ prévente).
	</data>
</document>
